rails_app/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users

  authenticated :user do
    root "posts#index", as: :authenticated_root
  end

  unauthenticated :user do
    root to: redirect("/users/sign_in"), as: :unauthenticated_root
  end

  resources :posts, only: [:index, :show] do
    resources :comments, only: [:create, :destroy, :edit, :update]
    collection { get 'aktualnosci' }
  end

  resources :contact_form, only: %i[index new create]

  namespace :admin do
    root to: "posts#index"

    resources :posts do
      resources :comments, only: [:create]
      member do
        post :generate_pdf
      end
    end

    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :users
    resources :pages, except: [:show] do
      post 'attachments', on: :member
    end

    # PDF
    get 'export_pdf', to: 'pdf#export', as: :export_pdf
    get 'download_pdf', to: 'pdf#download', as: :download_pdf

    # Strony w panelu
    get 'pages/*path', to: 'pages#show', as: :page_show,
        format: false, constraints: { path: /.*/ }
  end

  resources :pages, only: [:index]
  get 'pages/*path', to: 'pages#show', as: :page, format: false

  namespace :api, defaults: { format: :json } do
    resources :posts, only: [:index, :show]
    post "contact", to: "contact#create"
    resources :pages, only: [:index, :show]
    resources :comments, only: [:index, :show]
    resources :users, only: [:index, :show]
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

rails_app/app/views/admin/pages/_form.html.erb
<%= form_with model: [:admin, @page], local: true do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div>
    <%= f.label :content %>
    <%= f.rich_text_area :content %> 
  </div>

  <div>
    <%= f.label :published %>
    <%= f.check_box :published %>
  </div>

  <div>
    <%= f.label :position %>
    <%= f.number_field :position %>
  </div>

  <div class="mb-3">
  <%= f.label :parent_id, "Strona nadrzędna" %>
  <%= f.select :parent_id, 
      options_from_collection_for_select(
        Page.where.not(id: @page.id), 
        :id, 
        :title_with_path,
        @page.parent_id
      ),
      { include_blank: "Brak (strona główna)" },
      class: 'form-select'
  %>
</div>

  <%= f.submit %>
<% end %>

rails_app/app/views/admin/pages/edit.html.erb
<h1>Edit Page</h1>

<%= render 'form', page: @page %>


<%= link_to 'Back', admin_pages_path %>

rails_app/app/views/admin/pages/index.html.erb
<h1>Zarządzanie stronami</h1>

<%= link_to 'Nowa strona', new_admin_page_path, class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>Pozycja</th>
      <th>Tytuł</th>
      <th>Ścieżka</th>
      <th>Status</th>
      <th>Akcje</th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.position %></td>
        <td><%= page.title %></td>
        <td><%= page.full_path %></td>
        <td><%= page.published? ? 'Opublikowany' : 'Szkic' %></td>
        <td>
          <%= link_to 'Pokaż', admin_page_show_path(page.full_path) %>
          <%= link_to 'Edytuj', edit_admin_page_path(page.id) %>
          <%= button_to 'Usuń', admin_page_path(page), method: :delete, data: { confirm: 'Na pewno usunąć?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

rails_app/app/views/admin/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', admin_pages_path %>

rails_app/app/views/admin/pages/show.html.erb
<h1><%= @page.title %></h1>

<div class="page-content">
  <%= @page.content %>
</div>

<% if @child_pages.any? %>
  <div class="child-pages mt-4">
    <h3>Podstrony:</h3>
    <ul class="list-group">
      <% @child_pages.each do |child| %>
        <li class="list-group-item">
          <%= link_to child.title, admin_page_path(child.full_path) %>
          <% if child.published? %>
            <span class="badge bg-success ms-2">Opublikowana</span>
          <% else %>
            <span class="badge bg-warning ms-2">Szkic</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>



<div class="mt-4">
  <%= link_to 'Edytuj', edit_admin_page_path(@page), class: 'btn btn-primary' %>
  <%= link_to 'Powrót do listy', admin_pages_path, class: 'btn btn-secondary' %>
  
</div>